// 電源容量計算ツール — コンポーネント・電源データ

export interface ComponentSpec {
  id: string;
  name: string;
  category: "マイコン" | "センサー" | "表示" | "モーター" | "通信" | "LED" | "その他";
  typicalCurrent: number;  // 標準消費電流 (mA)
  peakCurrent: number;     // ピーク消費電流 (mA)
  voltage: number;         // 動作電圧 (V)
  note: string;
  amazonKeyword: string;
  partId?: string;         // パーツ辞典リンク用
}

export interface PowerSource {
  id: string;
  name: string;
  voltage: number;
  maxCurrent: number;  // mA
  type: "USB" | "ACアダプタ" | "電池" | "バッテリー";
  capacity?: number;   // mAh（バッテリー系のみ）
  amazonKeyword: string;
  pros: string[];
  cons: string[];
}

export const COMPONENT_SPECS: ComponentSpec[] = [
  // ── マイコン ──
  {
    id: "arduino-uno",
    name: "Arduino Uno",
    category: "マイコン",
    typicalCurrent: 50,
    peakCurrent: 200,
    voltage: 5,
    note: "USB給電時。外部電源7-12V可。GPIO出力は1ピンあたり最大40mA。",
    amazonKeyword: "Arduino Uno R3",
    partId: "arduino-uno-r4-wifi",
  },
  {
    id: "arduino-nano",
    name: "Arduino Nano",
    category: "マイコン",
    typicalCurrent: 20,
    peakCurrent: 200,
    voltage: 5,
    note: "小型で省電力。ブレッドボード直挿し可能。",
    amazonKeyword: "Arduino Nano",
  },
  {
    id: "esp32",
    name: "ESP32（WiFi動作時）",
    category: "マイコン",
    typicalCurrent: 240,
    peakCurrent: 500,
    voltage: 3.3,
    note: "WiFi送信時に瞬間的に500mA近く消費。Deep Sleep時は10μA以下。",
    amazonKeyword: "ESP32 DevKitC",
    partId: "esp32-devkitc",
  },
  {
    id: "esp32-sleep",
    name: "ESP32（Deep Sleep時）",
    category: "マイコン",
    typicalCurrent: 0.01,
    peakCurrent: 0.05,
    voltage: 3.3,
    note: "Deep Sleepモード。定期ウェイクアップで超低消費電力運用可能。",
    amazonKeyword: "ESP32 DevKitC",
    partId: "esp32-devkitc",
  },
  {
    id: "raspberry-pi-pico",
    name: "Raspberry Pi Pico",
    category: "マイコン",
    typicalCurrent: 25,
    peakCurrent: 90,
    voltage: 3.3,
    note: "RP2040搭載。低消費電力でバッテリー駆動に最適。",
    amazonKeyword: "Raspberry Pi Pico",
  },
  {
    id: "raspberry-pi-4b",
    name: "Raspberry Pi 4B",
    category: "マイコン",
    typicalCurrent: 600,
    peakCurrent: 1250,
    voltage: 5,
    note: "最低3A推奨の電源が必要。USB機器接続時はさらに増加。",
    amazonKeyword: "Raspberry Pi 4B",
    partId: "raspberry-pi-5",
  },
  {
    id: "m5stack-basic",
    name: "M5Stack Basic",
    category: "マイコン",
    typicalCurrent: 120,
    peakCurrent: 350,
    voltage: 5,
    note: "ESP32内蔵。LCD・スピーカー・バッテリー搭載のオールインワン。",
    amazonKeyword: "M5Stack Basic",
  },

  // ── センサー ──
  {
    id: "dht22",
    name: "DHT22 温湿度センサー",
    category: "センサー",
    typicalCurrent: 1.5,
    peakCurrent: 2.5,
    voltage: 3.3,
    note: "測定間隔2秒以上推奨。待機時0.5mA。",
    amazonKeyword: "DHT22 温湿度センサー",
    partId: "dht22",
  },
  {
    id: "bmp280",
    name: "BMP280 気圧センサー",
    category: "センサー",
    typicalCurrent: 0.3,
    peakCurrent: 1.1,
    voltage: 3.3,
    note: "I2C接続。超低消費電力でバッテリー駆動向き。",
    amazonKeyword: "BMP280 気圧センサー",
    partId: "bmp280",
  },
  {
    id: "hc-sr04",
    name: "HC-SR04 超音波距離センサー",
    category: "センサー",
    typicalCurrent: 15,
    peakCurrent: 30,
    voltage: 5,
    note: "測定範囲2cm〜400cm。5V動作のため3.3Vマイコンでは分圧が必要。",
    amazonKeyword: "HC-SR04 超音波センサー",
    partId: "hc-sr04",
  },
  {
    id: "pir-sensor",
    name: "PIRセンサー（人感）",
    category: "センサー",
    typicalCurrent: 0.1,
    peakCurrent: 0.15,
    voltage: 3.3,
    note: "待機電力が極小。セキュリティや自動照明に最適。",
    amazonKeyword: "PIRセンサー HC-SR501",
  },
  {
    id: "mq2-gas",
    name: "MQ-2 ガスセンサー",
    category: "センサー",
    typicalCurrent: 150,
    peakCurrent: 180,
    voltage: 5,
    note: "ヒーター内蔵で消費電力大。プリヒート時間24時間以上推奨。",
    amazonKeyword: "MQ-2 ガスセンサー",
  },
  {
    id: "bh1750",
    name: "BH1750 照度センサー",
    category: "センサー",
    typicalCurrent: 0.12,
    peakCurrent: 0.19,
    voltage: 3.3,
    note: "I2C接続の高精度照度センサー。1〜65535 lux。",
    amazonKeyword: "BH1750 照度センサー",
    partId: "bh1750",
  },
  {
    id: "mpu6050",
    name: "MPU6050 加速度・ジャイロ",
    category: "センサー",
    typicalCurrent: 3.8,
    peakCurrent: 5,
    voltage: 3.3,
    note: "6軸IMU（3軸加速度+3軸ジャイロ）。I2C接続。",
    amazonKeyword: "MPU6050 加速度 ジャイロ",
    partId: "mpu6050",
  },

  // ── 表示 ──
  {
    id: "oled-096",
    name: "OLED 0.96インチ（SSD1306）",
    category: "表示",
    typicalCurrent: 20,
    peakCurrent: 30,
    voltage: 3.3,
    note: "I2C/SPI接続。全白表示時に最大電流。黒多めで省電力。",
    amazonKeyword: "OLED 0.96 SSD1306",
  },
  {
    id: "lcd-1602",
    name: "LCD 16x2（バックライト付）",
    category: "表示",
    typicalCurrent: 2,
    peakCurrent: 120,
    voltage: 5,
    note: "バックライトONで120mA。OFFなら2mA。I2Cアダプタ推奨。",
    amazonKeyword: "LCD 1602 I2C",
  },
  {
    id: "neopixel-1",
    name: "NeoPixel 1個（WS2812B）",
    category: "表示",
    typicalCurrent: 20,
    peakCurrent: 60,
    voltage: 5,
    note: "全白最大輝度で60mA/個。色・輝度で電流が大きく変わる。",
    amazonKeyword: "NeoPixel WS2812B",
  },
  {
    id: "7seg-led",
    name: "7セグメントLED（1桁）",
    category: "表示",
    typicalCurrent: 80,
    peakCurrent: 140,
    voltage: 5,
    note: "各セグメント約10mA × 7 + DP。ダイナミック点灯で省電力化可能。",
    amazonKeyword: "7セグメント LED",
  },
  {
    id: "tft-24",
    name: "TFT 2.4インチ液晶",
    category: "表示",
    typicalCurrent: 60,
    peakCurrent: 100,
    voltage: 3.3,
    note: "SPI接続。バックライト含む。カラー表示可能。",
    amazonKeyword: "TFT 2.4インチ SPI",
  },
  {
    id: "e-paper-29",
    name: "電子ペーパー 2.9インチ",
    category: "表示",
    typicalCurrent: 8,
    peakCurrent: 30,
    voltage: 3.3,
    note: "更新時のみ電力消費。表示保持に電力不要で超省電力。",
    amazonKeyword: "電子ペーパー 2.9インチ",
  },

  // ── モーター ──
  {
    id: "sg90",
    name: "SG90 マイクロサーボ",
    category: "モーター",
    typicalCurrent: 150,
    peakCurrent: 500,
    voltage: 5,
    note: "無負荷時150mA、ロック時500mA以上。マイコンのGPIOから直接駆動しないこと。",
    amazonKeyword: "SG90 サーボモーター",
    partId: "sg90-servo",
  },
  {
    id: "dc-motor-small",
    name: "DCモーター（小型 FA-130）",
    category: "モーター",
    typicalCurrent: 200,
    peakCurrent: 600,
    voltage: 3,
    note: "起動時・ストール時に大電流。モータードライバ必須。",
    amazonKeyword: "FA-130 モーター",
    partId: "dc-motor-fa130",
  },
  {
    id: "stepper-28byj",
    name: "ステッピングモーター（28BYJ-48）",
    category: "モーター",
    typicalCurrent: 240,
    peakCurrent: 500,
    voltage: 5,
    note: "ULN2003ドライバボード付属が一般的。精密な角度制御が可能。",
    amazonKeyword: "28BYJ-48 ステッピングモーター",
    partId: "28byj-48-stepper",
  },
  {
    id: "fan-motor",
    name: "DCファンモーター（5V）",
    category: "モーター",
    typicalCurrent: 150,
    peakCurrent: 250,
    voltage: 5,
    note: "冷却用。PWMで回転数制御可能。",
    amazonKeyword: "5V DCファン 冷却",
  },
  {
    id: "vibration-motor",
    name: "振動モーター（コイン型）",
    category: "モーター",
    typicalCurrent: 80,
    peakCurrent: 100,
    voltage: 3,
    note: "フィードバック・通知用。小型で組込みやすい。",
    amazonKeyword: "振動モーター コイン型",
  },

  // ── 通信 ──
  {
    id: "esp8266",
    name: "ESP8266 WiFiモジュール",
    category: "通信",
    typicalCurrent: 170,
    peakCurrent: 430,
    voltage: 3.3,
    note: "WiFi送信時に大電流。安定した3.3V電源が必要。",
    amazonKeyword: "ESP8266 WiFi モジュール",
  },
  {
    id: "hc05-bluetooth",
    name: "HC-05 Bluetoothモジュール",
    category: "通信",
    typicalCurrent: 50,
    peakCurrent: 80,
    voltage: 3.3,
    note: "Bluetooth Classic SPP通信。ペアリング時に消費増。",
    amazonKeyword: "HC-05 Bluetooth",
  },
  {
    id: "lora-module",
    name: "LoRaモジュール（SX1278）",
    category: "通信",
    typicalCurrent: 12,
    peakCurrent: 120,
    voltage: 3.3,
    note: "送信時120mA、受信時12mA。長距離通信（数km）が可能。",
    amazonKeyword: "LoRa SX1278 モジュール",
  },
  {
    id: "gps-module",
    name: "GPSモジュール（NEO-6M）",
    category: "通信",
    typicalCurrent: 40,
    peakCurrent: 65,
    voltage: 3.3,
    note: "コールドスタートに数分かかる。バックアップ電池で高速起動。",
    amazonKeyword: "NEO-6M GPS モジュール",
  },
  {
    id: "nrf24l01",
    name: "nRF24L01 2.4GHz無線",
    category: "通信",
    typicalCurrent: 12,
    peakCurrent: 14,
    voltage: 3.3,
    note: "低消費電力な近距離無線。送受信ともに省電力。",
    amazonKeyword: "nRF24L01 無線モジュール",
  },

  // ── LED ──
  {
    id: "led-single",
    name: "砲弾型LED 1個（5mm）",
    category: "LED",
    typicalCurrent: 20,
    peakCurrent: 25,
    voltage: 2,
    note: "色により順方向電圧が異なる（赤2V, 緑2.2V, 青3.2V）。",
    amazonKeyword: "LED 5mm セット",
    partId: "led-5mm",
  },
  {
    id: "neopixel-strip-10",
    name: "NeoPixelストリップ 10個",
    category: "LED",
    typicalCurrent: 200,
    peakCurrent: 600,
    voltage: 5,
    note: "全白最大輝度で60mA/個×10。実用では1/3程度の輝度が多い。",
    amazonKeyword: "NeoPixel WS2812B ストリップ",
  },
  {
    id: "led-matrix-8x8",
    name: "LED Matrix 8x8（MAX7219）",
    category: "LED",
    typicalCurrent: 100,
    peakCurrent: 320,
    voltage: 5,
    note: "MAX7219ドライバICで制御。カスケード接続可能。",
    amazonKeyword: "LED Matrix 8x8 MAX7219",
  },
  {
    id: "led-ring-16",
    name: "NeoPixelリング 16個",
    category: "LED",
    typicalCurrent: 320,
    peakCurrent: 960,
    voltage: 5,
    note: "全白60mA/個×16。エフェクトにより平均電流は大幅に下がる。",
    amazonKeyword: "NeoPixel リング 16",
  },
];

export const POWER_SOURCES: PowerSource[] = [
  {
    id: "usb-20",
    name: "USB 2.0",
    voltage: 5,
    maxCurrent: 500,
    type: "USB",
    amazonKeyword: "USB ケーブル Type-B",
    pros: ["PCから給電可能", "ケーブル1本で接続", "最も手軽"],
    cons: ["500mAまで", "モーター駆動には不足しがち"],
  },
  {
    id: "usb-30",
    name: "USB 3.0",
    voltage: 5,
    maxCurrent: 900,
    type: "USB",
    amazonKeyword: "USB 3.0 ケーブル",
    pros: ["900mAまで対応", "センサー多数でもOK", "データ転送も高速"],
    cons: ["モーター複数は厳しい", "ポートの実力差がある"],
  },
  {
    id: "usb-pd",
    name: "USB PD（5V/3A）",
    voltage: 5,
    maxCurrent: 3000,
    type: "USB",
    amazonKeyword: "USB PD 充電器 5V 3A",
    pros: ["3Aの大容量", "スマホ充電器を流用可能", "安全性が高い"],
    cons: ["PD対応ケーブルが必要", "マイコン側もUSB-C推奨"],
  },
  {
    id: "ac-5v-2a",
    name: "ACアダプタ 5V/2A",
    voltage: 5,
    maxCurrent: 2000,
    type: "ACアダプタ",
    amazonKeyword: "ACアダプタ 5V 2A DCジャック",
    pros: ["安定した出力", "Raspberry Pi推奨", "比較的安価"],
    cons: ["コンセントが必要", "持ち運び不便"],
  },
  {
    id: "ac-9v-1a",
    name: "ACアダプタ 9V/1A",
    voltage: 9,
    maxCurrent: 1000,
    type: "ACアダプタ",
    amazonKeyword: "ACアダプタ 9V 1A",
    pros: ["Arduino Vin端子に最適", "レギュレーターで5V/3.3V生成", "ノイズが少ない"],
    cons: ["電圧が高く発熱注意", "電池駆動不可"],
  },
  {
    id: "ac-12v-2a",
    name: "ACアダプタ 12V/2A",
    voltage: 12,
    maxCurrent: 2000,
    type: "ACアダプタ",
    amazonKeyword: "ACアダプタ 12V 2A",
    pros: ["モーター・LEDストリップに最適", "高出力24W", "産業用途にも"],
    cons: ["3.3V/5Vには降圧が必要", "発熱に注意"],
  },
  {
    id: "battery-aa-4",
    name: "単3電池×4本",
    voltage: 6,
    maxCurrent: 2000,
    capacity: 2000,
    type: "電池",
    amazonKeyword: "単3電池 アルカリ",
    pros: ["どこでも入手可能", "持ち運び自由", "初心者に安全"],
    cons: ["電圧が徐々に低下", "長時間使用にはコスト高", "大電流に弱い"],
  },
  {
    id: "battery-aaa-4",
    name: "単4電池×4本",
    voltage: 6,
    maxCurrent: 800,
    capacity: 800,
    type: "電池",
    amazonKeyword: "単4電池 アルカリ",
    pros: ["軽量コンパクト", "入手性が良い", "ウェアラブル向き"],
    cons: ["容量800mAhと少ない", "大電流不可", "頻繁に交換が必要"],
  },
  {
    id: "battery-9v",
    name: "9V電池（006P）",
    voltage: 9,
    maxCurrent: 400,
    capacity: 500,
    type: "電池",
    amazonKeyword: "9V電池 アルカリ",
    pros: ["1個で9V出力", "Arduino Vin端子に直結可能", "コンパクト"],
    cons: ["容量が非常に小さい", "大電流に弱い", "コストパフォーマンス悪い"],
  },
  {
    id: "lipo-1000",
    name: "リポバッテリー 3.7V/1000mAh",
    voltage: 3.7,
    maxCurrent: 1000,
    capacity: 1000,
    type: "バッテリー",
    amazonKeyword: "リポバッテリー 3.7V 1000mAh JST",
    pros: ["軽量・大容量", "充電して繰り返し使える", "ESP32に最適"],
    cons: ["充電モジュールが別途必要", "取扱い注意（発火リスク）", "5V出力には昇圧が必要"],
  },
  {
    id: "lipo-2000",
    name: "リポバッテリー 3.7V/2000mAh",
    voltage: 3.7,
    maxCurrent: 2000,
    capacity: 2000,
    type: "バッテリー",
    amazonKeyword: "リポバッテリー 3.7V 2000mAh",
    pros: ["長時間駆動", "1C放電で2A出力可能", "IoTデバイス向き"],
    cons: ["サイズがやや大きい", "充電管理が必要", "過放電保護推奨"],
  },
  {
    id: "mobile-battery",
    name: "モバイルバッテリー 5V/2A",
    voltage: 5,
    maxCurrent: 2000,
    capacity: 10000,
    type: "バッテリー",
    amazonKeyword: "モバイルバッテリー 10000mAh",
    pros: ["大容量で長時間駆動", "5V安定出力", "USB接続で簡単"],
    cons: ["低電流時に自動OFFする機種あり", "サイズが大きい", "3.3Vには降圧が必要"],
  },
];

export const CATEGORIES = ["マイコン", "センサー", "表示", "モーター", "通信", "LED"] as const;

export const CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  "マイコン": { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200" },
  "センサー": { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  "表示": { bg: "bg-purple-50", text: "text-purple-700", border: "border-purple-200" },
  "モーター": { bg: "bg-red-50", text: "text-red-700", border: "border-red-200" },
  "通信": { bg: "bg-sky-50", text: "text-sky-700", border: "border-sky-200" },
  "LED": { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200" },
  "その他": { bg: "bg-gray-50", text: "text-gray-700", border: "border-gray-200" },
};

export const SAFETY_MARGIN = 0.2; // 20% 安全マージン
